version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  test: 
    jobs:
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          version: '14.16.0'
          pkg-manager: npm
          