version: 2.1

orbs:
    node: circleci/node@4.7

jobs:
    test:
        executor:
            name: node/default
            tag: '14.16.0'
        steps:
            - checkout
            - node/install-packages
            - run:
                  command: npm test
                  environment:
                      BASE_URL: 'https://jsonplaceholder.typicode.com/'
            - store_artifacts:
                  path: reports/jest_html_reporters.html
            - store_test_results:
                  path: reports/junit.xml

    static:
        executor:
            name: node/default
            tag: '14.16.0'
        steps:
            - checkout
            - node/install-packages
            - run: npm run lint
            - run: npm run prettier
            - run: npm run ts-check

workflows:
    build:
        jobs:
            - test
            - static
